ifeq ($(IS_OPLUS),true)
OPLUS_FEATURE_PROCESS_RECLAIM := yes
OPLUS_FEATURE_ZRAM_OPT := yes
OPLUS_FEATURE_EMMC_DRIVER := yes
OPLUS_FEATURE_EMMC_SDCARD_OPTIMIZE := yes
OPLUS_FEATURE_MULTI_KSWAPD := yes
OPLUS_FEATURE_MULTI_FREEAREA := yes
export OPLUS_FEATURE_PROCESS_RECLAIM OPLUS_FEATURE_ZRAM_OPT \
       OPLUS_FEATURE_EMMC_DRIVER OPLUS_FEATURE_EMMC_SDCARD_OPTIMIZE \
       OPLUS_FEATURE_MULTI_KSWAPD OPLUS_FEATURE_MULTI_FREEAREA
KBUILD_CFLAGS += -DOPLUS_FEATURE_PROCESS_RECLAIM \
                 -DOPLUS_FEATURE_ZRAM_OPT \
                 -DOPLUS_FEATURE_EMMC_DRIVER \
                 -DOPLUS_FEATURE_EMMC_SDCARD_OPTIMIZE \
                 -DOPLUS_FEATURE_MULTI_KSWAPD \
                 -DOPLUS_FEATURE_MULTI_FREEAREA
endif