ifeq ($(IS_OPLUS),true)
OPLUS_FEATURE_ZRAM_OPT := yes
OPLUS_FEATURE_HYBRIDSWAP := yes
export OPLUS_FEATURE_ZRAM_OPT OPLUS_FEATURE_HYBRIDSWAP
KBUILD_CFLAGS += -DOPLUS_FEATURE_ZRAM_OPT -DOPLUS_FEATURE_HYBRIDSWAP
endif