# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

oplus_binder_stats-objs := binder_stats_dev.o
obj-$(CONFIG_OPLUS_FEATURE_BINDER_STATS_ENABLE) += oplus_binder_stats.o

ccflags-y += -I$(srctree)/drivers/staging
